# Generated by Django 3.1.4 on 2020-12-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='ページ数')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('recruit_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='募集ID')),
                ('shop_ID', models.IntegerField(verbose_name='店舗ID')),
                ('recruit_title', models.CharField(default='NOT TITLE', max_length=500, verbose_name='募集タイトル')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='投稿時刻')),
                ('finish_time', models.DateTimeField(verbose_name='募集締め切り時刻')),
                ('person_type', models.CharField(max_length=300, verbose_name='職種')),
                ('person_number', models.IntegerField(blank=True, default=1, verbose_name='人数')),
                ('work_start_time', models.DateTimeField(verbose_name='開始時刻')),
                ('work_last_time', models.DateTimeField(verbose_name='終了時刻')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('finish_flag', models.BooleanField(default=0, verbose_name='マッチング前後')),
                ('password', models.CharField(max_length=40, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.book', verbose_name='書籍')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='応募ID')),
                ('shop_ID', models.IntegerField(blank=True, verbose_name='店舗ID')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='投稿時刻')),
                ('person_type', models.CharField(max_length=300, verbose_name='職種')),
                ('person_number', models.IntegerField(blank=True, default=1, verbose_name='人数')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('finish_flag', models.BooleanField(verbose_name='マッチング判定')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='cms.recruit', verbose_name='応募')),
            ],
        ),
    ]
