# Generated by Django 3.1.4 on 2020-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pty', models.CharField(max_length=300, verbose_name='職種')),
            ],
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='person_type',
        ),
        migrations.AddField(
            model_name='recruit',
            name='person_type',
            field=models.ManyToManyField(blank=True, to='cms.PType'),
        ),
    ]
