# Generated by Django 3.1.4 on 2020-12-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_ID', models.IntegerField(blank=True, default=0, verbose_name='募集ID')),
                ('shop_ID', models.IntegerField(blank=True, default=0, verbose_name='店舗ID')),
                ('post_time', models.TimeField(verbose_name='投稿時刻')),
                ('finish_time', models.TimeField(verbose_name='募集締め切り時刻')),
                ('person_type', models.IntegerField(blank=True, default=0, verbose_name='職種')),
                ('person_number', models.IntegerField(blank=True, default=1, verbose_name='人数')),
                ('work_start_time', models.TimeField(verbose_name='開始時刻')),
                ('work_last_time', models.TimeField(verbose_name='終了時刻')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('finish_flag', models.BooleanField(verbose_name='マッチング前後')),
                ('password', models.CharField(max_length=400, verbose_name='パスワード')),
                ('entry_ID', models.IntegerField(verbose_name='応募ID')),
            ],
        ),
    ]
