# Generated by Django 3.1.4 on 2020-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201206_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptype',
            name='pty',
            field=models.CharField(max_length=300, unique=True, verbose_name='職種'),
        ),
    ]
