# Generated by Django 3.1.4 on 2020-12-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_recruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_ID', models.IntegerField(blank=True, default=0, verbose_name='応募ID')),
                ('shop_ID', models.IntegerField(blank=True, default=0, verbose_name='店舗ID')),
                ('post_time', models.TimeField(verbose_name='投稿時刻')),
                ('person_type', models.IntegerField(blank=True, default=0, verbose_name='職種')),
                ('person_number', models.IntegerField(blank=True, default=1, verbose_name='人数')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('finish_flag', models.BooleanField(verbose_name='マッチング判定')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='cms.recruit', verbose_name='応募')),
            ],
        ),
    ]
