# Generated by Django 3.1.4 on 2020-12-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_recruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='id',
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruit_title',
            field=models.CharField(default='NOT TITLE', max_length=500, verbose_name='募集タイトル'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='finish_time',
            field=models.DateTimeField(verbose_name='募集締め切り時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='person_type',
            field=models.CharField(max_length=300, verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='post_time',
            field=models.DateTimeField(auto_now=True, verbose_name='投稿時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='募集ID'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='shop_ID',
            field=models.IntegerField(verbose_name='店舗ID'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='work_last_time',
            field=models.DateTimeField(verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='work_start_time',
            field=models.DateTimeField(verbose_name='開始時刻'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='応募ID')),
                ('shop_ID', models.IntegerField(blank=True, verbose_name='店舗ID')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='投稿時刻')),
                ('person_type', models.CharField(max_length=300, verbose_name='職種')),
                ('person_number', models.IntegerField(blank=True, default=1, verbose_name='人数')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('finish_flag', models.BooleanField(verbose_name='マッチング判定')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='cms.recruit', verbose_name='応募')),
            ],
        ),
    ]
