# Generated by Django 3.1.4 on 2020-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201205_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='entry_ID',
        ),
    ]
