# Generated by Django 3.1.4 on 2020-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='id',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='応募ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='person_type',
            field=models.CharField(max_length=300, verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='post_time',
            field=models.DateTimeField(auto_now=True, verbose_name='投稿時刻'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='shop_ID',
            field=models.IntegerField(blank=True, verbose_name='店舗ID'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='finish_time',
            field=models.DateTimeField(verbose_name='募集締め切り時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='person_type',
            field=models.CharField(max_length=300, verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='post_time',
            field=models.DateTimeField(auto_now=True, verbose_name='投稿時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='募集ID'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='shop_ID',
            field=models.IntegerField(verbose_name='店舗ID'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='work_last_time',
            field=models.DateTimeField(verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='work_start_time',
            field=models.DateTimeField(verbose_name='開始時刻'),
        ),
    ]
