# Generated by Django 3.1.4 on 2020-12-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201205_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='recruit_title',
            field=models.CharField(default='NOT TITLE', max_length=500, verbose_name='募集タイトル'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='password',
            field=models.CharField(max_length=40, verbose_name='パスワード'),
        ),
    ]
