# Generated by Django 3.1.4 on 2020-12-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20201206_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='recruit',
        ),
        migrations.AddField(
            model_name='entry',
            name='recruit_ID',
            field=models.IntegerField(default=1, verbose_name='募集ID'),
        ),
    ]
